-- H2 schema for JobRunStatsRepositoryTest
-- Mirrors BATCH_JOB_RUN_STATS / BATCH_STEP_RUN_STATS from schema-batch-stats.sql
-- but uses H2-compatible DDL (GENERATED BY DEFAULT AS IDENTITY, TIMESTAMP, etc.)

CREATE TABLE BATCH_JOB_RUN_STATS (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id   VARCHAR(50),
    job_execution_id BIGINT,
    job_name         VARCHAR(100),
    status           VARCHAR(20),
    start_time       TIMESTAMP,
    end_time         TIMESTAMP,
    duration_seconds INT,
    total_read       BIGINT,
    total_written    BIGINT,
    total_filtered   BIGINT,
    total_errors     BIGINT,
    config_hash      VARCHAR(50),
    error_summary    VARCHAR(2000),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BATCH_STEP_RUN_STATS (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_stats_id BIGINT,
    step_name    VARCHAR(100),
    status       VARCHAR(20),
    read_count   BIGINT,
    write_count  BIGINT,
    filter_count BIGINT,
    skip_count   BIGINT,
    error_detail VARCHAR(2000)
);
